### ISSUE TITLE
rtk_msgs

### ISSUE THREAD

**Issue by hordurk** [brNX/rtklibros#1]
Hello,

I wanted to try out your catkinized fork, but it will not build due to missing rtk_msgs package. Was that something you created? Do you have them somewhere in a repository?

Thanks

**Comment by brNX** [comment]
Hi,

sorry it has been in my todo list for a while , I reused the rtk_msgs package form the following repository https://github.com/goncabrita/rtk_gps

**Comment by hordurk** [comment]
Ok, thanks.
